name: yt_dlf
description: Flutter project to download youtube playlists. Basically yt-dl or yt-dlp but as an app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  async: ^2.9.0

  permission_handler: ^10.2.0
  path_provider: ^2.0.11
  file_picker: ^5.2.2

  youtube_explode_dart: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
